version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:v1.9.1-hotfix.6

    steps:
      - checkout

      - run:
          name: Install danger
          command: sudo gem install danger-flutter_lint && sudo gem install danger && danger

      - run:
          name: Check convension
          command: flutter analyze > flutter_analyze_report.txt
