version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:v1.9.1-hotfix.6

    steps:
      - checkout

      # - run:
      #     name: Run Flutter doctor
      #     command: flutter doctor

      # - run:
      #     name: Get packages
      #     command: flutter packages get

      - run:
          name: Install danger
          command: sudo gem install danger-flutter_lint

      - run:
          name: Check convention
          command: sh ci_check_convention.sh

      - run:
          name: Run danger
          command: danger
