version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter

    steps:
      - checkout

      - run:
          name: Install danger
          command: sudo gem install danger-flutter_lint

      - run:
          name: Check convension
          command: flutter analyze > flutter_analyze_report.txt
